### ISSUE TITLE
Добавить примеры коммитов (body и title и пр.)

### ISSUE THREAD

**Issue by NurOrNuLL** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#10]
## Конечный результат:
* Реализовать пример составления коммитов

## План решения:
* Написать примеры составления коммитов

## Мотивация:
* Нужна для того, чтобы структурированно делать коммиты

## Критерии приемки:
* Сделать изменение в проекте
* Добавить в гит
* Сделать коммит по этому примеру
* Сделать пуш
* На сайте посмотреть коммит

## Планируемое время выполнения:
* 30 минут

**Comment by asparukh01** [comment]
Фактическое время 30 минут
