### ISSUE TITLE
Добавить github action flake8

### ISSUE THREAD

**Issue by NurOrNuLL** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#11]
## Конечный результат:
* Добавить в github action flake8

## План решения:
* Добавить папку .github в корень проекта 
* Внутри .github создать папку workflows
* Добавить в workflows yml файл для проверки flake8

## Мотивация:
* Нужна для проверки кода перед мердж рекуестом своей ветки на ветку develop 

## Критерии приемки:
* Запушить локальную ветку
* Перейти на ветку develop
* Заппулить последние изменения ветки develop
* Отправить запрос на слияние рабочей ветки на ветку develop

## Планируемое время выполнения:
* 1 час

**Comment by Beka757** [comment]
фактическое время 2 часа
