### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by NurOrNuLL** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#12]
## Конечный результат:
* Написать страницу с быстрой установкой и интеграцией Swagger в Django

## План решения:
* Создать страницу Swagger в wiki
* Добавить ссылку на главную страницу
* Добавить ссылку в навигацию

## Мотивация:
* Для пользователей, которые зайдут к нам в проект и захотят посмотреть, какие библиотеки и технологии мы использовали

## Критерии приемки:
* Зайти в wiki, зайти на страницу Swagger через главную или навигацию, там прочитать про установку и интеграцию в Django

**Comment by Imrvrs** [comment]
Фактическое время выполнения - 20 минут
