### ISSUE TITLE
Версионирование API

### ISSUE THREAD

**Issue by NurOrNuLL** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#13]
## Конечный результат:
* Добавить статью по версионированию API

## План решения:
* В меню навигации вики в разделе "документация" cоздать ссылку на страницу со статьей по версионированию API
* Описать страницу с краткой информации о версионировании API, правилах применения в проекте

## Мотивация:
* Данная статья описывает

**Comment by asparukh01** [comment]
Фактическое время 1 час
