### ISSUE TITLE
Выделить основные бизнес модели и функционал

### ISSUE THREAD

**Issue by NurOrNuLL** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#15]
## Конечный результат:
* Добавлены основные бизнес модели и функционал

## План решения:
* Создать ссылку на страницу с выделенными для тикета "functional"
* Описать основные бизнес модели и функционал с лейблом "functional"

## Мотивация:
* Для лучшего понимания структуры проекта и дальнейшего планирования базы данных

## Критерии приемки:
* В меню навигации вики в разделе "Проектная документация" есть ссылка на описание бизнес моделей и функционала "functional"
* При переходе по этой ссылке открывается страница с описанием бизнес моделей и функционала

## Планируемое время выполнения:
* 1 час

**Comment by rusterz** [comment]
По задаче #15 выполнил за 1 час
