### ISSUE TITLE
Добавить правила для тикета "Docs"

### ISSUE THREAD

**Issue by NurOrNuLL** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#16]
## Конечный результат:
* Добавить правила для тикета "Docs"

## План решения:
* Создать ссылку на страницу с правилами для тикета "docs"
* Описать правила создания тикета с лейблом "docs"
* Добавить пример задачи с лейблом "docs"

## Мотивация:
* Данные правила необходимы для создания тикетов в едином стиле для удобства работы в команде и для облегчения восприятия задач новыми людьми при изучении проекта

## Критерии приемки:
* В меню навигации вики в разделе "правила"  есть ссылка на правила по созданию тикета "docs"
* При переходе по этой ссылке открывается страница с описанием правил

## Планируемое время выполнения:
* 1 час

**Comment by avamerina** [comment]
Фактическое время выполнения: 2 часа
