### ISSUE TITLE
Исправить вывод формы при создании контрагента

### ISSUE THREAD

**Issue by Beka757** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#184]
## Конечный результат:
* Реализовать вывод выбранной формы при не валидной форме

## План решения:
* Переписать js script для для вывода выбранной формы при не валидной форме
* Сделать поле наименование контрагента в модели не уникальным 

## Мотивация:
* При не валидной форме чтобы возвращалась та же форма которую мы выбрали при заполнении

## Критерии приемки:
* Перейти на страницу создания контрагента
* Откроется страница создания контрагента
* Выбрать создание физического лица, отправить не валидную форму
* Убедиться что форма осталась та же 
* Заполнить поле наименование контрагента несколько раз с одинаковыми данными и убедиться что это поле не уникальна

**Comment by rusterz** [comment]
Задача неактуальна.
