### ISSUE TITLE
Перенести статические файлы из aws в проект 

### ISSUE THREAD

**Issue by avamerina** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#186]
## Конечный результат:
* Перенести статические файлы из aws в директорию 'static' внутри проекта для удобства разработки

## План решения:
* Перенести статические файлы из aws в директорию для статики внутри проекта

## Мотивация:
*  Перенести все статические файлы кроме 'uploads' из aws в проект необходимо для быстрой загрузки статических файлов что ускорит процесс разработки

## Критерии приемки:
* Перенести статические файлы из aws в директорию для статики внутри проекта
* Проверить отображение стилей и работу функционала на страницах и убедиться, что все работает

**Comment by asparukh01** [comment]
Фактическое время 10 минут
