### ISSUE TITLE
Реализовать список заказ нарядов

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#308]
## Конечный результат:
* Список заказ нарядов на главной странице

## План решения:
* Написать url для списка заказ нарядов
* Написать view для списка заказ нарядов
* Написать фильтрацию заказ нарядов по дате, статусу заказ наряда, статусу оплаты
* Написать поиск по гос. номеру авто, фамилии контрагента
* Добавить шаблон для списка заказ нарядов
* Добавить ссылку на эту страницу в сайдбар

## Мотивация:
* Это нужно для просмотра созданных заказ нарядов и дальнейшей реализации с этой страницы детальной страницы и изменения статуса заказ наряда

## Критерии приемки:
* Зайти на главную страницу
* Проверить правильность отображения списка
* Проверить фильтры и поиск
* Попробовать зайти на эту страницу с сайдбара

**Comment by Beka757** [comment]
потраченное время 3 часа
