### ISSUE TITLE
Применить оптимистик лок для редактирования контрактора

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#311]
## Конечный результат:
* Оптимистик лок для редактирования контрагента

## План решения:
* Добавить в модель контрактора поле версии
* Добавить в view обработку конкуренции
* Добавить вывод подтверждения своих изменения при не совпадении версий

## Мотивация:
* Это нужно для защиты от перезатирания чужих изменений своими

## Критерии приемки:
* Запустить тесты на оптимистик лок
* Зайти на редактирование контрактора с двух аккаунтов одновременно
* Проверить вывод подтверждения

**Comment by rusterz** [comment]
Выполнил за 5 часов.

* Установил библиотеку django-concurrency и обновил requirements.txt
* Добавил поле версии в модель контрагента. Создал и применил миграции
* Описал логику обработки оптимистичной блокировки параллельных запросов в контроллере views.py
* Обработал новую логику в шаблоне редактирования контрагента
* Создал шаблон для отображения изменений данных контрагента при параллельных запросах
* Прописал роуты
* Обновил тест на редактирование контрагента
