### ISSUE TITLE
Подкорректировать список контракторов

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#316]
## Конечный результат:
* Список контракторов с сортировкой по имени в алфавитном порядке

## План решения:
* Дописать сортировку по имени в view списка
* В шаблоне убрать колонку таблицы id

## Мотивация:
* Это нужно для удобного вывода контракторов

## Критерии приемки:
* Зайти на страницу списка контракторов
* Проверить выше указанные требования

**Comment by avamerina** [comment]
время выполенения: 30 минут
