### ISSUE TITLE
Добавить кэширование в редис на Export exel

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#318]
## Конечный результат:
* Добавить кэширование в редис на Export exel 

## План решения:
* В настройках settings.py добавить настройки для кэширование в редис
* В таске для загрузки кешировать список номенклатур с прайсами
* В обновлениях спика номенклатур добавить удаления с кэша номенклатур для сохранения актуальных данных о номенклатуре

## Мотивация:
* Это нужно для ускорения работы приложения и уменьшения походов в базу за данными

## Критерии приемки:
* Запустить redis-cli и проверить keys *
* В составе ключей должен быть номенклатуры

**Comment by mollionline** [comment]
Фактическое время выполнения: 2 часа
