### ISSUE TITLE
Подкорректировать детальную страницу сотрудника

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#320]
## Конечный результат:
* Страница сотрудника без вывода картинки и с возможностью посмотреть в модальном окне и скачать картинку

## План решения:
* Убрать вывод картинки
* Добавить кнопку помотреть, которая будет открывать модальное окно
* Дописать view для скачивания фотографии

## Мотивация:
* Это нужно для удобной работы с фотографиями сотрудников

## Критерии приемки:
* Зайти на детальную страницу сотрудника
* Попробовать посмотреть фотографию
* Попробовать скачать фотографию

**Comment by asparukh01** [comment]
фактическое время 4 часа
