### ISSUE TITLE
Добавить начальные конфигурации логирования

### ISSUE THREAD

**Issue by avamerina** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#36]
## Конечный результат:
* Добавить начальные конфигурации логирования

## План решения:
* Добавить переменную конфигураций в файл settings.py
* Создать инстанс логера для последующего использования в файле views.py

## Мотивация:
* Логирование позволит нам вести отладку на этапе продакшна

## Критерии приемки:
* В файле настроек проекта есть переменная LOGGING с параметрами конфигураций логирования
* В файле views.py есть инстанс логера

**Comment by Beka757** [comment]
время выполнения 2 часа
