### ISSUE TITLE
Распределить разрешения (permissions) для пользоваталей сайта

### ISSUE THREAD

**Issue by mollionline** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#369]
## Конечный результат:
* Распределить permissions для пользовталей сайта

## План решения:
* Дописать в views методы для permissions

## Мотивация:
* Нужна для того, чтобы пользователям была доступна информация предназначенная для них в зависимости от должности в организации

## Критерии приемки:
* Перейти на сайт
* Авторизоваться как админ проверить все разрешения
* Авторизоваться как управляющий проверить все разрешения
* Авторизоваться как менеджер проверить все разрешения

**Comment by Beka757** [comment]
потраченное время 30 мин
