### ISSUE TITLE
Коррекция стилей отображения заголовков списка собственностей

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#470]
## Конечный результат:
* Коррекция стилей отображения заголовков на странице общего списка собственностей и на странице деталей контрагента

## План решения:
* Привести стили отображения заголовков к одному виду
* Привести размеры полей к одному значению
* Исключить перемещение заголовков в списке собственностей при смене типа собственности

## Мотивация:
* Необходимо для более приятного восприятия отображенной информации

## Критерии приемки:
* Перейти на страницу общего списка собственностей
* Убедиться, что при переключении типа собственности в фильтрах не прыгают заголовки
* Проверить то же самое на странице деталей контрагента

**Comment by avamerina** [comment]
Время выполнения: 30 минут
