### ISSUE TITLE
Коррекция страницы списка услуг

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#471]
## Конечный результат:
* Провести коррекцию списка услуг

## План решения:
* Центрировать цифру номера страницы (задать параметры: width 100px и text-align: center)
* Исправить опечатку на кнопке "форма для заполнения exel" заменить на "форма для заполнения excel"
* В модальном окне загрузки excel файла: Задать расстояние на нижней части кнопки "Выберите файл"
* Корректно отобразить сообщение "файл не выбран"
* Убрать поле выбора номенклатуры (получать её id из основного окна)
* Добавить "Drag and drop" - загрузку при перетаскивании файла с рабочего стола в модальное окно.
* Во view/service номенклатур применить фильтрацию для получаемых из БД номенклатур по текущему филиалу вместо objects.all

## Мотивация:
* Нужна для  кореектного отображения функционала страницы списка услуг

## Критерии приемки:
* Перейти на страницу списка услуг
* Убедиться, что отображается корректно
* Убедиться, что все работает

**Comment by Imrvrs** [comment]
Время выполнения - 2 часа
