### ISSUE TITLE
Реализовать редактирование номенклатуры с оптимистичной блокировкой параллельных запросов

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#472]
## Конечный результат:
* Реадактирование номенклатуры осуществляется с оптимистичной блокировкой параллельных запросов на обновление данных номенклатуры

## План решения:
* Добавить в модель номенклатуры поле версии из библиотеки django-conncurrency
* Описать логику в контроллере для редактирования и обработки конкуренции
* Написать url для редактирования номенклатуры
* Добавить шаблон для редактированиям номенклатуры
* Добавить ссылку на страницу редактирования выбранной номенклатуры на странице списка услуг
* Добавить вывод для подтверждения изменений при несовпадении версий номенклатуры

## Мотивация:
* Это нужно для редактирования уже имеющейся номенклатуры при опечатке или ошибочно введённых данных в момент её создания
* Необходимо для защиты от перезатирания чужих изменений своими
* Необходимо для поддержания консистентности базы

## Критерии приемки:
* Зайти на страницу списка услуг
* Перейти на редактирование номенклатуры
* Сохранить изменения и проверить корректность отработки простого редактирования
* Зайти на страницу редактирования номенклатуры с двух аккаунтов одновременно
* Попытаться изменить данные
* Проверить корректный вывод страницы подтверждения

**Comment by Beka757** [comment]
потраченное время 3 часа
