### ISSUE TITLE
Написать тест на оптимистичную блокировку параллельного обновления Номенклатуры

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#473]
## Конечный результат:
* Написать тест на оптимистичную блокировку параллельного обновления Номенклатуры

## План решения:
* Добавить в web/nomenclature папку tests
* Добавить файл test_nomenclature.py
* Написать тест

## Мотивация:
* Нужна для того, чтобы проверить корректность работы  оптимистичной блокировки 

## Критерии приемки:
* Провести тест и убедится что тест прошел успешно

**Comment by Imrvrs** [comment]
Время выполнения - 2 часа
