### ISSUE TITLE
Изменить редактирование филиала 

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#475]
## Конечный результат:
* Изменить редактирование филиала соовтетственно связи М2М поля nomenclature

## План решения:
* Обновить файл сервисов филиала
* Изменить логику редактирования филиала 
* Обновить формы редактирования филиала
* Обновить формы подтверждения изменений  в случае срабатывания оптимистичной блокировки, при паралельном редактировании филиала

## Мотивация:
* Нужна для корректной работы редактирования филиала

## Критерии приемки:
* Перейти на редактирования создания филиала
* Попытаться отредактировать филиал
* Зайти на страницу редактирования филиала с двух аккаунтов одновременно
* Попытаться изменить данные
* Проверить корректный вывод страницы подтверждения

**Comment by Beka757** [comment]
потраченное время 3 час
