### ISSUE TITLE
Коррекция создания сотрудника

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#476]
## Конечный результат:
* Коррекция создания сотрудника

## План решения:
* Скрыть поле Филиалы, и передавать филиал из текущего филиала, к которому относится пользователь
* На формах создания сотрудника (мастера и аккаунта) произвести локализацию (русификацию) полей выбора даты и файла
* Форму создания управляющего отображать без поля загрузки файла уд.лич (либо сделать поле необязательным для управляющего)
* Уведомление Alert JS об успешном создании сотрудника заменить на Alert Bootstrap и расположить модальное окно в центре

## Мотивация:
* Нужна корректной работы с созданием сотрудника

## Критерии приемки:
* Перейти на страницу создания сотрудника
* Попытаться создать сотрудника
* Убедиться, что все работает и отображается корректно

**Comment by asparukh01** [comment]
фактическое время 3 часа
