### ISSUE TITLE
Написать валидацию на ввод ИИН сотрудника по дате рождения

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#477]
## Конечный результат:
* Валидация на ввод ИИН сотрудника по дате рождения в форме создания сотрудника

## План решения:
* Написать логику валидации первых 6-ти цифр ИИН допускающего ввод данных даты рождения в формате YY-MM-DD

## Мотивация:
* Нужно для проверки корректнсти ввода поля ИИН

## Критерии приемки:
* Перейти на страницу создания сотрудника
* Убедиться в правильной отработке валидации ИИН

**Comment by asparukh01** [comment]
Фактическое время 3 часа
