### ISSUE TITLE
Доработка Wiki GitHub

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#478]
## Конечный результат:
* Доработанный Wiki GitHub

## План решения:
* Заменить навигацию в центре страницы на описание вступления о проекте (аудиозапись встречи с ментором за 23.06)
* В навигации в правой части страницы поднять раздел "О нас" в начало списка
* В разделе "О нас" добавить ссылку на отдельную страницу для каждого контрибьютора (для последующего заполнения инфрмации)
* Заполнить страницу об исполнителе данного тикета с применением mermaid GitHub https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
* Заполнить Readme (https://github.com/NurOrNuLL/ESDP-AP-5-6-TEAM-2#readme) описанием документации проекта (аудиозапись встречи с ментором за 23.06)
- Вставить ссылку на Wiki Home

## Мотивация:
* Необходимо для ознакомления проектом и его создателями

## Критерии приемки:
* Перейти в раздел GitHub "О нас"
* Перейти в раздел GitHub "Readme"
* Убедиться в наличии необходимой информации

**Comment by avamerina** [comment]
время выполнения 2 часа
