### ISSUE TITLE
Реализовать редактирование собственности с оптимистичной блокировкой параллельных запросов

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#479]
## Конечный результат:
* Реадактирование собственности осуществляется с оптимистичной блокировкой параллельных запросов на обновление данных номенклатуры

## План решения:
* Добавить в модель собственности поле версии из библиотеки django-conncurrency
* Описать логику в контроллере для редактирования и обработки конкуренции
* Написать url для редактирования собственности
* Добавить шаблон для редактированиям собственности
* Добавить ссылку на страницу редактирования выбранной собственности на странице списка собственностей контрагента, а также на общей странице собственностей всех контрагентов организации
* Добавить вывод для подтверждения изменений при несовпадении версий собственности

## Мотивация:
* Это нужно для редактирования уже имеющейся собственности при опечатке или ошибочно введённых данных в момент её создания
* Необходимо для защиты от перезатирания чужих изменений своими
* Необходимо для поддержания консистентности базы

## Критерии приемки:
* Зайти на страницу списка собственностей
* Перейти на редактирование собственности
* Сохранить изменения и проверить корректность отработки простого редактирования
* Зайти на страницу редактирования номенклатуры с двух аккаунтов одновременно
* Попытаться изменить данные
* Проверить корректный вывод страницы подтверждения

**Comment by asparukh01** [comment]
Фактическое время 8 часов
