### ISSUE TITLE
Написать тест на оптимистичную блокировку параллельного обновления собственности

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#480]
## Конечный результат:
* Написать тест на оптимистичную блокировку параллельного обновления Собственности

## План решения:
* Добавить в web/own папку tests
* Добавить файл test_own.py
* Написать тест

## Мотивация:
* Нужна для того, чтобы проверить корректность работы  оптимистичной блокировки 

## Критерии приемки:
* Провести тест и убедится что тест прошел успешно

**Comment by asparukh01** [comment]
Фактическое время 2 часа
