### ISSUE TITLE
Написать валидацию на ввод логина и пароля при создании аккаунта

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#481]
## Конечный результат:
* Валидация на ввод логина и пароля при создании аккаунта

## План решения:
* Написать логику валидации логина и пароля с выводом сообщения в форме в случае ошибки валидации

## Мотивация:
* Нужно для улучшения безопасности при создании логина и пароля

## Критерии приемки:
* Перейти на страницу создания аккаунта
* Убедиться в корректной отработке валидации логина и пароля

**Comment by Beka757** [comment]
Потраченное время 2 часа
