### ISSUE TITLE
Коррекция страницы списка заказ-нарядов

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#483]
## Конечный результат:
* Корректная страница списка заказ нарядов

## План решения:
* Центрировать цифру номера страницы (задать параметры: width 100px и text-align: center)
* В блоке поиска произвести локализацию (русификацию) полей выбора даты

## Мотивация:
* Нужна для корректного отображения функционала страницы списка заказ-нарядов

## Критерии приемки:
* Перейти на страницу списка заказ-нарядов
* Убедиться, что отображается корректно
* Убедиться, что все работает

**Comment by Beka757** [comment]
потраченное время  мин
