### ISSUE TITLE
Коррекция создания заказ-наряда с sidebar

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#484]
## Конечный результат:
* Корректное создание заказ-наряда соответственно изменённой связи с FK на М2М между моделями Филиалом и Номенклатурой, а также описанные в плане решения применённые исправления.

## План решения:
* Обновить логику получения номенклатуры и услуг в файлых views и services для редактирования заказ наряда
* Исключить возможность создания заказ-наряда с работами без назначенных мастеров-исполнителей
* Шаг 2. Если мастера на выбраны - исправить опечатку "мастера не ВЫБРАННЫ" заменить на "мастера не выбраны"
* Переименовать заголовок "Выбранные мастера" на "Мастера". 
* Возможно уменьшить шрифты на странице, чтобы минимизировать число переносов строк
* Шаг 3. Задать тексту во второй карточке отступ от правого края
* Шаг 4. Номер авто выводить одинаковым размером шрифта как у модели авто
* Везде убрать букву Т (тенге)
* При создании контрагента от заказ наряда настроить редирект обратно на заказ-наряд с заполненными данными контрагента
* При создании собственности от заказ настроить задать редирект обратно на заказ наряд с заполненными данными собственности

## Мотивация:
* Нужна корректного отображения и работы со страницей создания заказ-наряда

## Критерии приемки:
* Перейти на страницу создания заказ-наряда
* Попытаться создать заказ-наряд
* Убедиться, что все работает и отображается корректно

**Comment by Imrvrs** [comment]
Время выполнения 3 часа
