### ISSUE TITLE
Коррекция страницы просмотра заказ-наряда

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#485]
## Конечный результат:
* Корректная страницы просмотра заказ-наряда

## План решения:
* Отобразить цифры цен на работы по гарантии в перечеркнутом виде, чтобы выглядело также как при создании ЗН
* Исправить опечатку в заголовке графы "Катагория", заменить на  "Категория"

## Мотивация:
* Нужна для корректной работы со страницей просмотра заказ-наряда

## Критерии приемки:
* Перейти на страницу просмотра заказ-наряда
* Убедиться, что отображается корректно
* Убедиться, что все работает

**Comment by Imrvrs** [comment]
Время выполнения 5 минут
