### ISSUE TITLE
Коррекция создания номенклатуры

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#486]
## Конечный результат:
* Коррекция создания номенклатуры

## План решения:
* Изменить редирект после создания номенклатуры на страницк списка услуг с выбранной номенклатурой

## Мотивация:
* Нужна для корректной работы с функционалом создания номенклатуры

## Критерии приемки:
* Перейти на страницу создания номенклатуры
* Попытаться создать заказ-наряд
* Убедиться, что все работает и отображается корректно

**Comment by Imrvrs** [comment]
Время выполнения - 1 час
