### ISSUE TITLE
Обновить редактирование заказ наряда 

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#492]
## Конечный результат:
* Обновить редактирование заказ наряда соответственно изменённой с FK на М2М связи между моделями Филиала и Номенклатуры

## План решения:
* Обновить логику views для редактирования заказ наряда
* Обновить логику services получения номенклатуры и услуг

## Мотивация:
* Нужно для корректной работы функционала редактирвания заказ-наряда после изменённий связи моделей

## Критерии приемки:
* Перейти на страницу редактирования заказ-наряда
* Попытаться отредактировать заказ-наряд
* Убедиться, что все работает и отображается корректно

**Comment by Imrvrs** [comment]
Время выполнения 1 час
