### ISSUE TITLE
Валидация на странице добавления собственности

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#498]
## Конечный результат:
* Валидация на странице добавления собственности

## План решения:
* Написать валидацию на обязательность ввода поле госномера при создании автомобиля
* Изменить заголовок страницы "Добавить Собственность" на "Добавить собственность"

## Мотивация:
* Нужна валидации создания автомобилей

## Критерии приемки:
* Перейти на страницу добавления собственности
* Попробовать создать автомобиль без гос.номера
* Попробовать создать автомобиль с гос.номером
* Попробовать создать запчасть
* Убедиться, что всё работает корректно

**Comment by Imrvrs** [comment]
Время выполнения 30 минут
