### ISSUE TITLE
Реализовать список запчастей на странице контрагента

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#499]
## Конечный результат:
* Список запчастей на странице контрагента

## План решения:
- Вводить список автомобилей либо запчастей по нажатию кнопки кнопки "Автомобили" "Запчасти"  (по умолчанию выводить автомобили)
- Менять заголовок "Список автомобилей" на "Список запчастей" и обратно динамически в зависимости от выбранного типа списка собственностей
- Менять заголовок "Номер" на "Комментарий" в зависимости от выбранного типа списка собственностей
- В зависимости от выбранного типа списка собственностей, при удалении менять сообщение в модальном окне

## Мотивация:
* Нужно для возможности работать со списком запчастей контрагента

## Критерии приемки:
* Перейти на страницу контрагента
* Посмотреть два варианат списков 
* Попробовать удалить автомобиль
* Попробовать удалить запчасть
* Убедиться, что все работает и отображается корректно

**Comment by avamerina** [comment]
время выполнения: 10 часов
