### ISSUE TITLE
Реализовать полноценное создание заказ-наряда со страницы просмотра контрагента

### ISSUE THREAD

**Issue by rusterz** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#511]
## Конечный результат:
* Полноценное создание заказ-наряда со страницы просмотра контрагента

## План решения:
* Дополнить views для создания заказ-наряда со страницы просмотра контрагента
* Обновить шаблоны создания заказ-наряда со страницы просмотра контрагента

## Мотивация:
* Нужно для того, чтобы пользователь создавать заказ-наряды со страницы просмотра контрагента

## Критерии приемки:
* Перейти на страницу просмотра контрагента
* Создать заказ-наряд
* Убедиться что данные контрагента и собственности автоматически передаются на страницу создания заказ-наряда
* Убедиться, что все работает и отображается корректно

**Comment by Imrvrs** [comment]
Время выполнения 10 минут
