### ISSUE TITLE
Создать организацию

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#52]
## Конечный результат:
* Модель организации и запись в ней

## План решения:
* Подключить postgres
* Cоздать суперюзера
* Создать фикстуры
* Написать модель организации 
[Ссылка на базу](https://drive.google.com/file/d/18s_1JZCT9cPy1tHQEv5hNJSJF8vhOPm2/view?usp=sharing)
* Зарегистрировать модель организации в админ панели
* Создать там одну запись с данными организации

## Мотивация:
* Нужна для того, чтобы от этой записи обращаться к другим сущностям

## Критерии приемки:
* Применить миграцию, проверить наличие таблицы
* Зайти в админ панель и посмотреть запись в этой таблице

**Comment by mollionline** [comment]
Фактическое время выполнения: 3 часа
