### ISSUE TITLE
Создать модель услуги

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#53]
## Конечный результат:
* Модель услуги

## План решения:
* Создать модель услуги
[Ссылка на базу](https://drive.google.com/file/d/18s_1JZCT9cPy1tHQEv5hNJSJF8vhOPm2/view?usp=sharing)
* Зарегистрировать в админ панели

## Мотивация:
* Нужна для сохранения данных о услугах данной кампании

## Критерии приемки:
* Зайти в админ панель
* Посмотреть там услуги, попробовать создать

**Comment by Beka757** [comment]
Потраченное время 1,5 часа
