### ISSUE TITLE
Список услуг

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#54]
## Конечный результат:
* Страница, где отображается список всех услуг, 

## План решения:
* Написать view для списка услуг
* Написать шаблон для списка услуг
* Написать url для списка услуг
* Реализовать сортировку и поиск по полям: Наименование, Категория, Ценовая категория

## Мотивация:
* Страница нужна для просмотра всех услуг и поиска нужных услуг

## Критерии приемки:
* Перейти на url списка услуг
* Создать несколько тестовых данных
* Проверить сортировку и поиск

**Comment by asparukh01** [comment]
Фактическое время 3 часа
