### ISSUE TITLE
Редактирование услуг на странице списка при помощи api

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#55]
## Конечный результат:
* Реализовать редактирование цены и наименования в списке

## План решения:
* Написать сериализатор для услуги
* Написать api view
* Написать url для api
* Добавить модальное окно в шаблон
* Написать ajax запрос на редактирование *PATCH метод*

## Мотивация:
* Редактирование нужно для изменения данных при их надобности или ошибке при добавлении

## Критерии приемки:
* Перейти на страницу списка
* Проверить редактирование через модальное окно

**Comment by NurOrNuLL** [comment]
@Beka757 какой-то абстрактный тикет, ничего не понятно.
