### ISSUE TITLE
Исправить конкурентное редактирование заказ наряда

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#556]
## Конечный результат:
* Рабочий оптимистик лок для редактирование заказ наряда

## План решения:
* Исправить баг после конкурентного редактирования с неправильным отображением общей суммы

## Мотивация:
* Это нужно для правильного учета общей суммы после редактирования

## Критерии приемки:
* Проверить этот баг

**Comment by rusterz** [comment]
Выполнил за 30 минут

* Исправил логику расчёта стоимостей при параллельном обновлении
* Обновил шаблон
