### ISSUE TITLE
Исправить пропадаение кнопки после поиска контрагентов

### ISSUE THREAD

**Issue by mollionline** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#557]
## Конечный результат:
* Исправить пропадаение кнопки после поиска контрагентов

## План решения:
* При поиске контрагентов в списке пропадает кнопка на детальную страницу 

## Мотивация:
* Это нужно для корректной работы списка контрагентов

## Критерии приемки:
* Проверить страницу списка контрагентов

**Comment by Imrvrs** [comment]
Время выполнения - 20 минутт
