### ISSUE TITLE
При редактировании котрагентов  редактирование ИИН/БИН надо исключить

### ISSUE THREAD

**Issue by mollionline** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#559]
## Конечный результат:
* При редактировании котрагентов  редактирование ИИН/БИН надо исключить

## План решения:

* Добавить шаблон для авторизации

## Мотивация:
* Нужна для того, чтобы пользователь смог авторизоваться. Если он не авторизуется, тогда не сможет пользоваться программой.

## Критерии приемки:
* Перейти на сайт
* Откроется страница авторизации
* Авторизоваться и убедиться, что все работает

**Comment by rusterz** [comment]
Выполнил за 20 минут
