### ISSUE TITLE
В списке сотрудников при поиске сбивается бейдж с его ролью

### ISSUE THREAD

**Issue by mollionline** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#560]
## Конечный результат:
* В списке сотрудников при поиске сбивается бейдж с его ролью

## План решения:
* Исправить js скрипт который рендерит страницу

## Мотивация:
* Это нужно для правильного отображения ролей сотрудников в списке

## Критерии приемки:
* Попробовать поиск сотрудников

**Comment by Imrvrs** [comment]
Время выполнения 5 минут
