### ISSUE TITLE
На странице редактирования сотрудника включить редактирование картинки 

### ISSUE THREAD

**Issue by mollionline** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#561]
## Конечный результат:
* На странице редактирования сотрудника включить редактирование картинки 

## План решения:
* Реализовать отображение изображения на странице редактирования

## Мотивация:
* Необходимо для удобства работы функции редактирования сотрудника

## Критерии приемки:
* Перейти на страницу редактирования мастера
* Убедиться что отображается существующее фото сотрудника
* Попробовать изменить фото удостоверения сотрудника
* Убедиться, что редактирование прошло корректно

**Comment by avamerina** [comment]
время выполнения: 3 часа)
