### ISSUE TITLE
Убрать кнопку детали контрагента в списке собственностей

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#562]
## Конечный результат:
* Правильное отображение кнопки деталей контрагента

## План решения:
* Убрать кнопку детали контрагента
* Сделать ссылкой на контрагента его наименование

## Мотивация:
* Это нужно для более удобного использования

## Критерии приемки:
* Попробовать перейти по ссылке на детали контрагента

**Comment by Beka757** [comment]
потраченное время 15 мин
