### ISSUE TITLE
На странице редактирования филиала поменять кнопку Список на К списку

### ISSUE THREAD

**Issue by mollionline** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#563]
## Конечный результат:
* На странице редактирования филиала поменять кнопку Список на К списку

## План решения:
* Написать urls для авторизации
* Написать views для авторизации
* Добавить шаблон для авторизации

## Мотивация:
* Нужна для того, чтобы пользователь смог авторизоваться. Если он не авторизуется, тогда не сможет пользоваться программой.

## Критерии приемки:
* Перейти на сайт
* Откроется страница авторизации
* Авторизоваться и убедиться, что все работает

**Comment by Imrvrs** [comment]
Время выполнения - 5 минут
