### ISSUE TITLE
Поменять редирект на список филиалов при создании филиала

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#564]
## Конечный результат:
* После создания филиала делать редирект на список филиалов

## План решения:
* Поменять редирект на список филиалов

## Мотивация:
* Это нужно для удобного использования создания филиала

## Критерии приемки:
* Попробовать создать филиал

**Comment by Beka757** [comment]
потраченное время 5 мин
