### ISSUE TITLE
Скрыть кнопки на которых у пользователей нет прав

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#568]
## Конечный результат:
* Страницы с только с кнопками на которые у пользователя есть права

## План решения:
* Убрать кнопки на которые у пользователя нет прав

## Мотивация:
* Это нужно для минимализации вывода ошибки 403 для пользователя

## Критерии приемки:
* Проверить страницы

**Comment by Beka757** [comment]
потраченное время 3 часа
