### ISSUE TITLE
Запретить редактировать заказ наряд если он завершен и оплачен

### ISSUE THREAD

**Issue by yujiqo** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#571]
## Конечный результат:
* Запрет на редактирование заказ няряда если он завершен и оплачен

## План решения:
* Дописать permission для этого
* Убрать кнопку редактирования если заказ наряд завершен и оплачен

## Мотивация:
* Это нужно для создания конечного состояния заказ наряда

## Критерии приемки:
* Проверить запрет

**Comment by avamerina** [comment]
время выполнения: 30 минут
