### ISSUE TITLE
Добавить о websocket протоколе в wiki

### ISSUE THREAD

**Issue by yujiqo** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#572]
## Конечный результат:
* Страница в вики с информацией о websocket

## План решения:
* Создать страницу
* Добавить ссылку на главную и сайдбар

## Мотивация:
* Это нужно для осведомления о используемой технологии

## Критерии приемки:
* Проверить страницу в wiki

**Comment by asparukh01** [comment]
Фактическое время 1 час
