### ISSUE TITLE
Добавить автоматическую капитализацию имени и фамилии сотрудника

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#573]
## Конечный результат:
* Авто капитализация имени и фамилии сотрудника при создании и редактировании

## План решения:
* Добавить capitalyze для name и surname перед сохранением в базу

## Мотивация:
* Это нужно для правильного формата записи в базу имени и фамилии сотрудника

## Критерии приемки:
* Попробовать создать и отредактировать сотрудника

**Comment by mollionline** [comment]
Уже реализовано
