### ISSUE TITLE
Сделать уведомление после импорта и экспорта прайс листа

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#574]
## Конечный результат:
* Уведомление о успешном импорте и экспорте прайс листа даже при переходе на другую страницу

## План решения:
* Придумать решение и дописать текущий функционал

## Мотивация:
* Это нужно для того чтобы пользователь не был привязан к одной странице при импорте и экспорте прайс листа

## Критерии приемки:
* Проверить уведомление

**Comment by mollionline** [comment]
Здачи в тикете описаны в другом тикете, так как они повторяются, я закрываю текущий тикет
