### ISSUE TITLE
Реализовать создание очереди

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#583]
## Конечный результат:
* Создание очереди

## План решения:
* Написать модель очереди
* Написать views для создания очереди

## Мотивация:
* Это нужно для создание очередей если торговы точки заняты

## Критерии приемки:
* Попробовать создать очередь

**Comment by rusterz** [comment]
Выполнил за 2 часа
