### ISSUE TITLE
Исправить конфигурацию nginx для вебсокетов

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#586]
## Конечный результат:
* Рабочий nginx для websocket протокола

## План решения:
* Исправить конфигурацию nginx

## Мотивация:
* Это нужно для успешного деплоя на сервер

## Критерии приемки:
* Попробовать на сервере сформировать отчет

**Comment by Beka757** [comment]
Потраченное время 10 часов
