### ISSUE TITLE
Загрузка excel файла с услугами

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#59]
## Конечный результат:
* Реализовать загрузку excel файла с услугами в базу данных

## План решения:
* Переписать view для регистрации в админку
* Написать view для импорта данных из excel
* Добавить шаблон с кнопкой для импорта данных из excel
* Добавить в навигацию ссылку на страницу импорта

## Мотивация:
* Импорт нужен для быстрого старта работы с нашим приложением и избежания большого количества рутинной работы

## Критерии приемки:
* Перейти на страницу импорта через навигацию
* Проверить импорт данных 
* Зайти в админ панель и посмотреть результат выполнения

**Comment by Imrvrs** [comment]
Время выполнения - 3 часа

**Comment by NurOrNuLL** [comment]
@Imrvrs  какой excell файл?

**Comment by Imrvrs** [comment]
> @Imrvrs  какой excell файл? Каким способом нужно загрузить этот файл?

в формате .xls .xslx .csv в виде таблицы
