### ISSUE TITLE
Реализовать экспорт прайс листа в Excel

### ISSUE THREAD

**Issue by Beka757** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#61]
## Конечный результат:
* Реализовать выгрузку прайс листа в Excel на странице списка услуг

## План решения:
* Написать view для экспорта данных в Excel
* Добавить кнопку экспорта в шаблон списка
* Написать url для экспорта

## Мотивация:
* Нужна для того, чтобы управляющий смог экспортировать услуги из прайс листа в Excel.

## Критерии приемки:
* Зайти на страницу 'Импорт и экспорт услуги из excel'
* Выбрать расширение и Нажать на кнопку 'Экспортировать'
* Сохранить Excel файл в формате . xlsx .xls .csv на свой компьютер
* Убедиться что нужный  прайс лист удачно импортировался в Excel

**Comment by NurOrNuLL** [comment]
@Beka757 Каким должен быть конечный файл?

**Comment by mollionline** [comment]
> @Beka757 Каким должен быть конечный файл?

> Импорт сделали в форматах .xslx, .xls, .csv, наверное экспорт будет в таких же форматах

**Comment by Beka757** [comment]
Исправил

**Comment by mollionline** [comment]
Фактическое время выполнения: 2 часа
