### ISSUE TITLE
Исправить список заказ нарядов

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#619]
## Конечный результат:
* Удобный список заказ нарядов с понятным интерфейсом

## План решения:
* Убрать выделенный кружок у номера заказ наряда
* Вместо id написать №
* Поменять класс бутстрап таблицы на table-hover
* Ссылкой на деталку заказ наряда сделать всю строчку
* Сделать кнопку оплатить справой стороны, оставить возможность оплатить нажав на статус

## Мотивация:
* Это нужно для удобного и понятного интерфейса

## Критерии приемки:
* Проверить изменения

**Comment by mollionline** [comment]
Реализовано в другом тикете
