### ISSUE TITLE
Создать номенклатуру

### ISSUE THREAD

**Issue by mollionline** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#62]
## Конечный результат:
* Модель номенклатуры и запись в ней

## План решения:
* Написать модель для номенклатуры
* [ссылка на базу](https://drive.google.com/file/d/18s_1JZCT9cPy1tHQEv5hNJSJF8vhOPm2/view)
* Зарегистрировать модель организации в админ панели
* Обновить фикстуру

## Мотивация:
* Нужна для того, чтобы компоновать список услуг

## Критерии приемки:
* Применить миграцию, проверить наличие таблицы
* Зайти в админ панель и посмотреть запись в этой таблице

**Comment by mollionline** [comment]
Фактическое время выполнения: 1 час

**Comment by mollionline** [comment]
Фактическое время выполнения: 20 минут

**Comment by mollionline** [comment]
Фактическое время выполнения: 20 минут

**Comment by NurOrNuLL** [comment]
- Написать модель для номенклатуры
- Зарегистрировать модель организации в админ панели

что за такой план решения ? для чего регистрировать организацию ? 

Мало вводной информации.
