### ISSUE TITLE
Исправить оплату

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#621]
## Конечный результат:
* Рабочая и удобная оплата

## План решения:
* Добавить сумму для оплаты
* Перенести кнопку Оплатить на уровень к кнопке Закрыть
* Сделать поля Безналичной оплаты обязательными

## Мотивация:
* Это нуджо для удобной оплаты

## Критерии приемки:
* Проверить изменения

**Comment by mollionline** [comment]
Фактическое время выполнения: 4 часа
