### ISSUE TITLE
 Добавить в wiki про celery, redis, worker

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#83]
## Конечный результат:
* В wiki во вкладке библиотека должна быть ссылка на страницу "О работе с сelery, redis, flower"

## План решения:
* Создать страницу в Библиотеке
* Добавить ссылку на страницу в навигацию и главную страницу

## Мотивация:
* Это нужно для простого ознакомления с celery, redis, worker, для тех кто будет смотреть наш проект

## Критерии приемки:
* Зайти в wiki по 
* Проверить наличие ссылки на страницу в навигации и главной страницы [О работе с сelery, redis, flower](https://github.com/NurOrNuLL/ESDP-AP-5-6-TEAM-2/wiki/%D0%9E-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5--c-Celery-Redis-Flower)
* Зайти по ссылке на страницу и прочитать ее

**Comment by mollionline** [comment]
Фактическое время выполнения: 2 часа
