### ISSUE TITLE
Переписать все url'ы: в начале добавить 'org/<int:orgID>/tp/<int:tpID>'

### ISSUE THREAD

**Issue by Imrvrs** [NurOrNuLL/ESDP-AP-5-6-TEAM-2#84]
## Конечный результат:
* Нормальные url, которые будут исходить от организации и торговой точки, для удобного их переключения

## План решения:
* Дописать 'org/<int:orgID>/tp/<int:tpID>' в начале каждого пути
* Добавить редирект на главную если у нас будет пустой url

## Мотивация:
* Это нужно для удобной будущей реализации переключения торговых точек для менеджеров

## Критерии приемки:
* Запустить приложение, увидеть редирект на главную
* Проверить url

**Comment by Beka757** [comment]
потраченное время 30 мин
